/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {
    'hashPassword': string;
    'hashPasswordCrackTime': string;
    'password': string;
    'passwordCrackTime': string;
    'passwordEmpty': boolean;
    'passwordScore': number;
    'passwordStrengthColor': string;
    'passwordStrengthLabel': string;
    'passwordStrengthValue': number;
  }
  interface AppRoot {}
  interface OptrDecodeField {
    'disabled': boolean;
    'value': string;
  }
  interface OptrField {
    'infoCallback': Function;
    'inputChange': Function;
    'label': string;
    'placeholder': string;
    'strengthColor': string;
    'strengthIndicator': boolean;
    'strengthLabel': string;
    'strengthValue': number;
    'value': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLOptrDecodeFieldElement extends Components.OptrDecodeField, HTMLStencilElement {}
  var HTMLOptrDecodeFieldElement: {
    prototype: HTMLOptrDecodeFieldElement;
    new (): HTMLOptrDecodeFieldElement;
  };

  interface HTMLOptrFieldElement extends Components.OptrField, HTMLStencilElement {}
  var HTMLOptrFieldElement: {
    prototype: HTMLOptrFieldElement;
    new (): HTMLOptrFieldElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'optr-decode-field': HTMLOptrDecodeFieldElement;
    'optr-field': HTMLOptrFieldElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {
    'hashPassword'?: string;
    'hashPasswordCrackTime'?: string;
    'password'?: string;
    'passwordCrackTime'?: string;
    'passwordEmpty'?: boolean;
    'passwordScore'?: number;
    'passwordStrengthColor'?: string;
    'passwordStrengthLabel'?: string;
    'passwordStrengthValue'?: number;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface OptrDecodeField extends JSXBase.HTMLAttributes<HTMLOptrDecodeFieldElement> {
    'disabled'?: boolean;
    'value'?: string;
  }
  interface OptrField extends JSXBase.HTMLAttributes<HTMLOptrFieldElement> {
    'infoCallback'?: Function;
    'inputChange'?: Function;
    'label'?: string;
    'placeholder'?: string;
    'strengthColor'?: string;
    'strengthIndicator'?: boolean;
    'strengthLabel'?: string;
    'strengthValue'?: number;
    'value'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'optr-decode-field': OptrDecodeField;
    'optr-field': OptrField;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


