/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "./stencil.core";

export namespace Components {
  interface OptrApp {
    autofill: boolean;
    hashPassword: string;
    hashPasswordCrackTime: string;
    modifier: string;
    password: string;
    passwordCrackTime: string;
    passwordEmpty: boolean;
    passwordScore: number;
    passwordStrengthColor: string;
    passwordStrengthLabel: string;
    passwordStrengthValue: number;
  }
  interface OptrDecodeField {
    autofill: boolean;
    disabled: boolean;
    value: string;
  }
  interface OptrField {
    infoCallback: Function;
    inputChange: Function;
    label: string;
    placeholder: string;
    strengthColor: string;
    strengthIndicator: boolean;
    strengthLabel: string;
    strengthValue: number;
    value: string;
  }
}

declare global {
  interface HTMLOptrAppElement extends Components.OptrApp, HTMLStencilElement {}
  var HTMLOptrAppElement: {
    prototype: HTMLOptrAppElement;
    new (): HTMLOptrAppElement;
  };

  interface HTMLOptrDecodeFieldElement
    extends Components.OptrDecodeField,
      HTMLStencilElement {}
  var HTMLOptrDecodeFieldElement: {
    prototype: HTMLOptrDecodeFieldElement;
    new (): HTMLOptrDecodeFieldElement;
  };

  interface HTMLOptrFieldElement
    extends Components.OptrField,
      HTMLStencilElement {}
  var HTMLOptrFieldElement: {
    prototype: HTMLOptrFieldElement;
    new (): HTMLOptrFieldElement;
  };
  interface HTMLElementTagNameMap {
    "optr-app": HTMLOptrAppElement;
    "optr-decode-field": HTMLOptrDecodeFieldElement;
    "optr-field": HTMLOptrFieldElement;
  }
}

declare namespace LocalJSX {
  interface OptrApp extends JSXBase.HTMLAttributes<HTMLOptrAppElement> {
    autofill?: boolean;
    hashPassword?: string;
    hashPasswordCrackTime?: string;
    modifier?: string;
    password?: string;
    passwordCrackTime?: string;
    passwordEmpty?: boolean;
    passwordScore?: number;
    passwordStrengthColor?: string;
    passwordStrengthLabel?: string;
    passwordStrengthValue?: number;
  }
  interface OptrDecodeField
    extends JSXBase.HTMLAttributes<HTMLOptrDecodeFieldElement> {
    autofill?: boolean;
    disabled?: boolean;
    onOnCopy?: (event: CustomEvent<any>) => void;
    value?: string;
  }
  interface OptrField extends JSXBase.HTMLAttributes<HTMLOptrFieldElement> {
    infoCallback?: Function;
    inputChange?: Function;
    label?: string;
    placeholder?: string;
    strengthColor?: string;
    strengthIndicator?: boolean;
    strengthLabel?: string;
    strengthValue?: number;
    value?: string;
  }

  interface IntrinsicElements {
    "optr-app": OptrApp;
    "optr-decode-field": OptrDecodeField;
    "optr-field": OptrField;
  }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}
